###REGISTER USER
POST http://localhost:4500/user/register
Content-Type: application/json

{
    "fullname":"Sandra Chege",
    "username": "sandrachege123",
    "email":"9superbikes@gmail.com",
    "password":"12345678"
}

###LOGIN USER
POST http://localhost:4500/user/login
Content-Type: application/json

{
    "email":"9superbikes@gmail.com",
    "password":"12345678"
}

###CHECK USER DETAILS
GET http://localhost:4500/user/checkuserdetails
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI1NzA4NGIwNS0wYWExLTQwZWItODY5Mi1mNmE4MWIxMjNhYzUiLCJlbWFpbCI6IjlzdXBlcmJpa2VzQGdtYWlsLmNvbSIsImZ1bGxuYW1lIjoiU2FuZHJhIENoZWdlIiwidXNlcm5hbWUiOiJzYW5kcmFjaGVnZTEyMyIsInJvbGUiOiJ1c2VyIiwicHJvZmlsZVVybCI6Im5vLWltYWdlIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsInJlc2V0UGFzc3dvcmQiOmZhbHNlLCJPVFAiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIzLTEyLTEyVDIxOjEzOjMzLjUyN1oiLCJpYXQiOjE3MDI0MDQ4MTUsImV4cCI6MTcwMjQ5MTIxNX0.rbe2rrD43E0kGLS9giBjX56paKMiqjlM1045Aj9xZPw

###GET ALL USERS
GET http://localhost:4500/user/getallusers
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI1NzA4NGIwNS0wYWExLTQwZWItODY5Mi1mNmE4MWIxMjNhYzUiLCJlbWFpbCI6IjlzdXBlcmJpa2VzQGdtYWlsLmNvbSIsImZ1bGxuYW1lIjoiU2FuZHJhIENoZWdlIiwidXNlcm5hbWUiOiJzYW5kcmFjaGVnZTEyMyIsInJvbGUiOiJ1c2VyIiwicHJvZmlsZVVybCI6Im5vLWltYWdlIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsInJlc2V0UGFzc3dvcmQiOmZhbHNlLCJPVFAiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIzLTEyLTEyVDIxOjEzOjMzLjUyN1oiLCJpYXQiOjE3MDI0MDQ4MTUsImV4cCI6MTcwMjQ5MTIxNX0.rbe2rrD43E0kGLS9giBjX56paKMiqjlM1045Aj9xZPw

###getoneuser
POST http://localhost:4500/user/getoneuser
Content-Type: application/json

{
    "email": "9superbikes@gmail.com"
}

###updateuser
PUT http://localhost:4500/user/updateuser
Content-Type: application/json

{
    "userID":"57084b05-0aa1-40eb-8692-f6a81b123ac5",
    "fullname": "Sandra Chege",
    "profileUrl": "https://cdn.pixabay.com/photo/2023/11/21/00/09/ai-generated-8402112_1280.png",
    "profileCaption": "Embarking on literary adventures where every page is a portal to another world, unlocking emotions unexplored. In the realm of books, I traverse landscapes of imagination, dance with diverse characters, and taste the sweetness of words. Closing each book, I carry fragments of these extraordinary journeys into the tapestry of my real-world existence."
}

#### FORGOT PASSWORD
POST http://localhost:4500/user/forgot 
Content-Type: application/json

{
    "email":"9superbikes@gmail.com"
}

###RESET PASSWORD
POST http://localhost:4500/user/resetpassword
Content-Type: application/json

{
    "userID": "a7e3ce62-67ae-46e7-a824-0a1ac94b00b8",
    "password": "12345678"
}